### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by XJDHDR** [IceReaper/ebfd-re#1]
Would it be possible to add a license for the code in this repo? Without a license, all rights to this code are reserved, which means no one is allowed to do anything until they personally ask every contributor for permission.

If you want some suggestions, here are my favourites:

- [MPL 2.0](https://www.mozilla.org/en-US/MPL/2.0/): If you want a license that requires authors of derivative work to share their source code, without requiring the sharing of source code that merely links to the code.
- [MIT](https://en.wikipedia.org/wiki/MIT_License): If you want a permissive license that removes most restrictions on your IP.
- [CC0](https://creativecommons.org/public-domain/cc0/): If you want to release your work in the public domain, with a fallback for countries that don't allow people to do so.

I don't recommend the GPL, as this requires anyone that even links to your code to also license their software under the GPL and is incompatible with licenses that add restrictions not found in the GPL.

**Comment by IceReaper** [comment]
I'll add MIT soon if I don't forget about it :)

**Comment by XJDHDR** [comment]
Thank you.
